### ISSUE TITLE
unhelpful error message when trying to clone a protected projects

### ISSUE THREAD

**Issue by jdleesmiller** [winstonli/writelatex-git-bridge#8]
Since protected projects aren't yet supported, you can't yet clone them. At the moment, we seem to give the generic 'fatal: remote error: Overleaf server not available. Please try again later.' message. It would be better to give a more specific message if possible.

Does this require additional API support?

**Comment by winstonli** [comment]
The behaviour upon trying to clone a protected project is currently undefined. What currently happens on the API side of things?

**Comment by jdleesmiller** [comment]
As just noted, you should get a 403 status and
```
{
"status": 403,
"message": "Forbidden"
}
```
